name: Bug Report
description: You have an issue with the UAD-ng software itself
title: "bug(scope): "
labels: ["bug"]
body:
- type: checkboxes
  id: duplicate-issue
  attributes:
    label: I've made sure the reported issue doesn't exist yet.
    options:
      - label: Yes I did
        required: true
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: suggested-solution
  attributes:
    label: You have a solution?
    description: What to do to fix the issue.
- type: textarea
  id: logfiles
  attributes:
    label: Provide logs
    description: Upload the logfile generated by UAD-ng. See https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#where-are-the-logfiles for the location of logfiles.
  validations:
    required: true
